services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"   # AMQP порт
      - "15672:15672" # Порт управления
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  kitchen-1:
    image: kitchen
    build:
      context: .
      dockerfile: Kitchen/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  kitchen-2:
    image: kitchen
    build:
      context: .
      dockerfile: Kitchen/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-board:
    image: notificationboard
    build:
      context: .
      dockerfile: NotificationBoard/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy